train_mode: point
loss_type: ll
learner: adam
learning_rate: 1e-4
l2_norm: 1e-4
weight_decay: 1e-4
max_epochs: 100
eval_step: 1
clip_grad_norm: {'max_norm': 5, 'norm_type': 2}
train_batch_size: 2048
eval_batch_size: 1024
device: 'cuda:3'
checkpoint_dir: saved_models/ind
eval_mode: all
list_len: 100
topks: [1,5,10]
num_trials: 2
continue_metric: AUC
eval_metric_bigger: True
seed: 1111
reproducibility: False

have_hist: True
hist_dict: data/tmall/feateng_data/hist_dict_
hist_len_dict: data/tmall/feateng_data/hist_len_dict_

batch_neg_size: 5
