ml-1m: {
  model_name: cold,
  embed_dim: 32,
  hidden_dims: [128, 64],
  dropout: 0.8,
  use_hist: False
}

tmall: {
  model_name: cold,
  embed_dim: 16,
  hidden_dims: [128, 64],
  dropout: 0.5,
  use_hist: False
}

alipay: {
  model_name: cold,
  embed_dim: 16,
  hidden_dims: [128, 64],
  dropout: 0.5,
  use_hist: False
}

tiangong: {
  model_name: cold,
  embed_dim: 32,
  hidden_dims: [128, 64],
  dropout: 0.5,
  use_hist: False
}

