ml-1m: {
  model_name: dssm,
  embed_dim: 32,
  hidden_dims: [128, 64],
  dropout: 0.9,
  use_hist: False
}

tmall: {
  model_name: dssm,
  embed_dim: 16,
  hidden_dims: [128, 64],
  dropout: 0.5,
  use_hist: False,
  # batch_random_neg: True  
}


alipay: {
  model_name: dssm,
  embed_dim: 16,
  hidden_dims: [128, 64],
  dropout: 0.5,
  use_hist: False,
  # batch_random_neg: True
}

tiangong: {
  model_name: dssm,
  embed_dim: 32,
  hidden_dims: [128, 64],
  dropout: 0.1,
  use_hist: False,
  # batch_random_neg: True
}