tmall: {
  model_name: youtubednn,
  embed_dim: 16,
  hidden_dims: [128, 64],
  dropout: 0.5,
  use_hist: True,
  batch_random_neg: False
}

alipay: {
  model_name: youtubednn,
  embed_dim: 16,
  hidden_dims: [128, 64],
  dropout: 0.5,
  use_hist: True,
  batch_random_neg: False
}

tiangong: {
  model_name: youtubednn,
  embed_dim: 32,
  hidden_dims: [128, 64],
  dropout: 0.5,
  use_hist: False
}